language: csharp
solution: AdventOfCode.sln
install:
  - nuget restore AdventOfCode.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release AdventOfCode.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./AdventOfCode.Tests/bin/Release/AdventOfCode.Tests.dll